# Site settings
title: Tarttelin Family
description: > # this means to ignore newlines until "baseurl:"
  All about the Tarttelin Family
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tarttelin.github.io" # the base hostname & protocol for your site
twitter_username: pyruby
github_username:  tarttelin

# Build settings
markdown: redcarpet

collections: 
  wildlife:
    output: true
    display: Wildlife around Deans Farm
    icon: tree-deciduous
  saskcow:
    output: true
    display: Saskcow Games
    icon: knight
  freya:
    output: true
    display: random projects
    icon: wrench
